apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo
  region: us-east-2

nodeGroups:
  - name: myNodeGroup
    instanceType: t2.small
    desiredCapacity: 2
    amiFamily: Ubuntu2004 #node is ubuntu based
    ssh: # use existing EC2 key
      publicKeyName: docker

