apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo
  region: us-east-2

nodeGroups:
  - name: mynode-group
    instanceType: t3.medium
    desiredCapacity: 2
    amiFamily: Ubuntu2004 #node is ubuntu based
    ssh: # use existing EC2 key
      publicKeyName: docker

